server:
    #you can change the server port here
  port: 8080
  error:
    whitelabel:
        #disable whitelabel errors
        enabled: false
#this is where you format the logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger.%M - %msg%n"